package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-06T17:39:18.140-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "HotelWS")
@XmlSeeAlso({ObjectFactory.class})
public interface HotelWS {

    @WebMethod
    @RequestWrapper(localName = "getAllHotelsByState", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetAllHotelsByState")
    @ResponseWrapper(localName = "getAllHotelsByStateResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetAllHotelsByStateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.revature.ws.Hotel> getAllHotelsByState(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllHotels", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetAllHotels")
    @ResponseWrapper(localName = "getAllHotelsResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetAllHotelsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.revature.ws.Hotel> getAllHotels();
}
