package com.revature.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-03T21:05:00.218-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "HotelWSImplService",
                  wsdlLocation = "http://localhost:8080/SearchService/hotelservice?wsdl",
                  targetNamespace = "http://ws.revature.com/")
public class HotelWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.revature.com/", "HotelWSImplService");
    public final static QName HotelWSImplPort = new QName("http://ws.revature.com/", "HotelWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SearchService/hotelservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelWSImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SearchService/hotelservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HotelWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HotelWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HotelWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HotelWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HotelWS
     */
    @WebEndpoint(name = "HotelWSImplPort")
    public HotelWS getHotelWSImplPort() {
        return super.getPort(HotelWSImplPort, HotelWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelWS
     */
    @WebEndpoint(name = "HotelWSImplPort")
    public HotelWS getHotelWSImplPort(WebServiceFeature... features) {
        return super.getPort(HotelWSImplPort, HotelWS.class, features);
    }

}
