package com.revature.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-06T19:48:37.401-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "RoomWSImplService",
                  wsdlLocation = "http://localhost:8080/SearchService/roomservice?wsdl",
                  targetNamespace = "http://ws.revature.com/")
public class RoomWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.revature.com/", "RoomWSImplService");
    public final static QName RoomWSImplPort = new QName("http://ws.revature.com/", "RoomWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SearchService/roomservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RoomWSImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SearchService/roomservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RoomWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RoomWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoomWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RoomWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RoomWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RoomWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RoomWS
     */
    @WebEndpoint(name = "RoomWSImplPort")
    public RoomWS getRoomWSImplPort() {
        return super.getPort(RoomWSImplPort, RoomWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoomWS
     */
    @WebEndpoint(name = "RoomWSImplPort")
    public RoomWS getRoomWSImplPort(WebServiceFeature... features) {
        return super.getPort(RoomWSImplPort, RoomWS.class, features);
    }

}
